name: Terraform Security Scan

on:
  push:
    branches:
      - test/checkov
jobs:
  checkov-scan:

    name: Checkov IaC Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov scan on terraform root
        run: |
          checkov \
            --directory terraform \
            --framework terraform \
            --output cli \
            --output json \
            --output-file-path console,checkov-report-terraform.json \
            --download-external-modules true \
            --check "CKV_GCP*" \
            --quiet \
            --soft-fail

      - name: Run Checkov scan on common
        run: |
          checkov \
            --directory terraform/common \
            --framework terraform \
            --output cli \
            --output json \
            --output-file-path console,checkov-report-common.json \
            --download-external-modules true \
            --check "CKV_GCP*" \
            --quiet \
            --soft-fail

      - name: Run Checkov scan on dev environment
        run: |
          checkov \
            --directory terraform/environments/dev \
            --framework terraform \
            --output cli \
            --output json \
            --output-file-path console,checkov-report-dev.json \
            --download-external-modules true \
            --check "CKV_GCP*" \
            --quiet \
            --soft-fail

      - name: Run Checkov scan on production environment
        run: |
          checkov \
            --directory terraform/environments/production \
            --framework terraform \
            --output cli \
            --output json \
            --output-file-path console,checkov-report-production.json \
            --download-external-modules true \
            --check "CKV_GCP*" \
            --quiet \
            --soft-fail

      # - name: Run Checkov scan on insecure-storage module
      #   run: |
      #     checkov \
      #       --directory terraform/modules/insecure-storage \
      #       --framework terraform \
      #       --output cli \
      #       --output json \
      #       --output-file-path console,checkov-report-insecure-storage.json \
      #       --download-external-modules true \
      #       --check "CKV_GCP*" \
      #       --quiet \
      #       --soft-fail

      - name: Run Checkov scan on vulnerable-db module
        run: |
          checkov \
            --directory terraform/modules/vulnerable-db, terraform/modules/insecure-storage \
            --framework terraform \
            --output cli \
            --output json \
            --output-file-path console,checkov-report-vulnerable-db.json \
            --download-external-modules true \
            --check "CKV_GCP*" \
            --quiet \
            --soft-fail

      - name: Upload Checkov results
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: checkov-report
          path: |
            checkov-report-terraform.json
            checkov-report-common.json
            checkov-report-dev.json
            checkov-report-production.json
            # checkov-report-insecure-storage.json
            checkov-report-vulnerable-db.json
